# Generated by Django 4.0 on 2021-12-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.ManyToManyField(to='product.Category'),
        ),
    ]
