# Generated by Django 4.0 on 2021-12-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_categories_category_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='subcategories',
        ),
    ]
