# Generated by Django 4.0 on 2021-12-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_categories_category_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, to='product.Category'),
        ),
    ]
