# Generated by Django 4.0 on 2021-12-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
    ]
